server:
  port: 6000
spring:
  application:
    name: atguigu-crowd-project
  redis:
    host: 124.0.0.2
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
aliyun:
  oss:
    access-key-id:
    access-key-secret: 
    bucket-domain:
    bucket-name: 
    end-point: http: