server:
  port: 5000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka

zuul:
  ignored-services: "*"
  routes:
    crowd-portal:
      service-id: atguigu-crowd-auth
      path: /**
    crowd-project:
      service-id: atguigu-crowd-project
      path: /project/**
    crowd-order:
      service-id: atguigu-crowd-order
      path: /order/**
    crowd-pay:
      service-id: atguigu-crowd-pay
      path: /pay/**

  sensitive-headers: "*"
spring:
  application:
    name: atguigu-crowd-zuul
  redis:
    host: 124.0.0.2
  session:
    store-type: redis